### ISSUE TITLE
markview: wrong hash

### ISSUE THREAD

**Issue by 4evy** [elythh/nixvim#10]
Hey, I was trying to update nixvim but I couldn't since markview has a wrong hash...

```
specified: sha256-w6yn8aNcJMLRbzaRuj3gj4x2J/20wUROLM6j39wpZek=
got:       sha256-keMlFGBcu9ZXdiwbGYE+qBrGeo55+qhE/JgFeb+4fhM=
```

I tried running `nix-prefetch-git` and got same new hash:

```console
$ nix-shell -p nix-prefetch-git --run 'nix-prefetch-git --url https://github.com/OXY2DEV/markview.nvim --rev 8537f7f03e4683b9ef98202e7a0286373a5b7135 --quiet | jq .hash'

"sha256-keMlFGBcu9ZXdiwbGYE+qBrGeo55+qhE/JgFeb+4fhM="
```

https://github.com/elythh/nixvim/blob/3da7a7845a50028c3de956482b00c28457b5e3a8/config/plug/utils/markview.nix#L10

**Comment by elythh** [comment]
Oops, bumped the rev and forgot to bump the hash ! Thanks for the notice, fixed it 3bd57dd5d545a4962f8600a1fb43c09e0150eea7

**Comment by 4evy** [comment]
Oh nice, thanks for the quick fix, I was just about to post a PR 😄

**Comment by elythh** [comment]
I've seen your commit, you can create the PR if you want, it still updates markview to the most recent revision 😄
