### ISSUE TITLE
Treesitter for Nu not working

### ISSUE THREAD

**Issue by 0fie** [elythh/nixvim#2]
Hello. Have you managed to get Treesitter for Nu working?

**Comment by elythh** [comment]
Hey !
I don't read/edit nu files so I'm not able to tell you. Although from what I found there's [a treesitter for nu](https://github.com/nushell/tree-sitter-nu).
You might be able to add it to the treesitter configuration using one of these options
https://nix-community.github.io/nixvim/plugins/treesitter/index.html?highlight=treesitter#pluginstreesittermoduleconfig

**Comment by elythh** [comment]
Also https://github.com/nix-community/nixvim/issues/1319#issuecomment-2018150634 for the solution

**Comment by elythh** [comment]
aa1682084a408cd17ca43e2fd7ae245b0333b5e3 should do the trick

![satty-20240402-15:01:19](https://github.com/elythh/nixvim/assets/50964650/4a037833-7415-4819-ab32-059305be9eb0)

**Comment by 0fie** [comment]
It now works perfectly! Thanks!
