### ISSUE TITLE
Does the formatters get downloaded?

### ISSUE THREAD

**Issue by haru02w** [elythh/nixvim#22]
This is not a issue, I just couldn't find where formatters declared in [conform.nix](https://github.com/elythh/nixvim/blob/main/config/plug/lsp/conform.nix) are added to the nix-store.
Shouldn't they be added at `extraPackages`?

**Comment by haru02w** [comment]
Oh, they're being installed by the none-ls plugin. Got it

**Comment by elythh** [comment]
indeed ! for the missing ones they should be added as extra packages tho, you're right
