### ISSUE TITLE
enabling Obsidian causes conflicts/errors with oil and telescope

### ISSUE THREAD

**Issue by hobo1618** [elythh/nixvim#23]
Hey! 

Thanks so much for the awesome config. I've forked the repo and it's been a great way to learn nixvim. Everything generally works super well together, but I'm getting a little stuck with how to integrate Obsidian correctly.

When I enable obsidian in nixvim, I get an error when loading neovim because, presumably I don't have "work" and "home" directories created. So i created those at `~/obsidian/work` and `~/obsidian/home` and the loading error goes away and I can create new notes with Obsidian. But now oil.nvim and telescope both cause errors.

It also seems as though Obsidian is recursively recreating the `home/` and `work/` directories when I create new notes, which I imagine is probably the main issue.

Are there any specific changes I have to make to the config to enable Obsidian without conflicts, etc?

I can provide more detailed info if it's useful, of course.

Any help/hints much appreciated.

**Comment by elythh** [comment]
Hello !

Thanks for the kinds words ! I'm glad you're liking my nixvim configuration as a starting point.
You are right about obsidian, the current setup is too personal. When you try to enable it, it will except the folders your mentioned. I should declare that configuration somewhere else ([eg. in my NixOS config](https://github.com/elythh/flake/blob/0d9576c35cfaf9d4fd80d628e8d506213808daf8/modules/home/opt/nvim/nixvim.nix#L35)).

About your Telescope and Oil issue, I'm not sure where the conflict happens. I would appreciate the logs if you have them.

Meanwhile, I would advise you to delete every configuration you find under `plugins.obsidian.settings` that doesn't suit your needs. And refer to the [Nixvim documentation](https://nix-community.github.io/nixvim/plugins/obsidian/index.html?highlight=obsidian#obsidian) or the [official plugin repo doc](https://github.com/epwalsh/obsidian.nvim) to set it to your liking. 

```nix
{
  plugins.obsidian = {
    enable = true;
    settings = {
      completion = {
        min_chars = 2;
        nvim_cmp = true;
      };
      new_notes_location = "current_dir";
      mappings = {
        gf = {
          action = "require('obsidian').util.gf_passthrough";
          opts = {
            noremap = false;
            expr = true;
            buffer = true;
          };
        };
        "<leader>ch" = {
          action = "require('obsidian').util.toggle_checkbox";
          opts.buffer = true;
        };
      };
    };
  };
}
```
Is a great starting point and shouldn't conflict with other plugins such as Telescope and Oil

EDIT: It is indeed NOT a great starting point 😆 You need to specify at least 1 workspace when using Obsidian
```nix
{
  plugins.obsidian = {
    enable = true;
    settings = {
      completion = {
        min_chars = 2;
        nvim_cmp = true;
      };
      new_notes_location = "current_dir";
      workspaces = [
       {
         name = "default";
         path = "~/Documents";
       }
      ];
      mappings = {
        gf = {
          action = "require('obsidian').util.gf_passthrough";
          opts = {
            noremap = false;
            expr = true;
            buffer = true;
          };
        };
        "<leader>ch" = {
          action = "require('obsidian').util.toggle_checkbox";
          opts.buffer = true;
        };
      };
    };
  };
}
```

**Comment by hobo1618** [comment]
Lol yeah I noticed when I changed the config, but the error was more obvious now. 
Everything seems to be working perfectly! I think the errors with oil and telescope just had to do with the weird recursive vault creation. 
At any rate deleting the templates etc solved the problem.
Thanks so much!
