### ISSUE TITLE
Provide Instruction for how to install this nixvim into your profile officially

### ISSUE THREAD

**Issue by jgarte** [elythh/nixvim#34]
Hi,

WDYT if you were to provide instructions for how to install this nixvim into your profile officially? I'm newb.

**Comment by elythh** [comment]
Hello ! 
Sorry for the late reply. Have you read the README ? It has install instruction for basically every way you can imagine. 
If you want to install it using home-manager you first need to add the input in your `flake.nix`
```nix
 inputs = {
    nixvim.url = "github:elythh/nixvim";
 };
 ```
 Then you simply need to import the flake and you can add the package to your profile using 
 ```nix
 { inputs, ...}:
{
  home.packages = [ inputs.nixvim.packages."x86_64-linux".default]
}
```

**Comment by jgarte** [comment]
Hi, thanks for the info. If I want to install your repo, I run `home-manager switch` from the root of the elythh/nixvim repository to install the profile? 🦆

**Comment by jgarte** [comment]
Essentially, the workflow I am envisioning is that I clone your repo and install it. I don't want to run it ephemerally with `nix run .` but I want to install it to my home profile so that the nvim command is available on my system (Fedora Workstation). I have nix installed. 🦆

**Comment by elythh** [comment]
I see !
The easiest and most straightforward command would be to alias `nvim` to `nix run github:elythh/nixvim`. This doesn't require you to do anything else than install Nix and enable `flakes` and `nix-commands`
If you want to install my config as a package, you will need to use NixOS (this distribution) or [home-manager](https://github.com/nix-community/home-manager) (can be used on any distribution) along with flakes.
I have example for both of these in the README but TLDR:
- Add my flake as an input in your `flake.nix`
- Add my nixvim package to your package list

**Comment by elythh** [comment]
> Hi, thanks for the info. If I want to install your repo, I run home-manager switch from the root of the elythh/nixvim repository to install the profile? 🦆

No, this repository does not expose any home-manager profile. You would need to declare your own configuration to be able to run `home-manager switch`

**Comment by elythh** [comment]
>  I want to install it to my home profile

If you already have a flake that you use, you can do what I described [here](https://github.com/elythh/nixvim/issues/34#issuecomment-2513142866). That way the next time your do `home-manager switch` my Nixvim configuration will be in your path accessible with the `nvim` command

**Comment by jgarte** [comment]
Hi, I ended up resolving my question by cloning the repo and running `nix profile install .`.

**Comment by elythh** [comment]
I didn't even know that was possible, glad you were able to resolve your issue 😄
