### ISSUE TITLE
Error: the <down> key is disabled

### ISSUE THREAD

**Issue by officialrajdeepsingh** [elythh/nixvim#8]
up, down, right and left key is doesn't work.

![up key isdiabled error in nixvim](https://github.com/elythh/nixvim/assets/32416397/1d7d1519-76e8-4f7d-9429-818a422db9ed)

**Comment by elythh** [comment]
Hello ! Indeed this is because of https://github.com/m4xshen/hardtime.nvim

I've just pushed a commit to disable it by default if you want 1f2840f47234a38f34fedaf7a24275ab52012178 😄
