### ISSUE TITLE
Error related to Copilot.

### ISSUE THREAD

**Issue by officialrajdeepsingh** [elythh/nixvim#9]
Default copilot is enabled in nixvim. Some developers who don't use Copilot show the following error in nixvim.

![coplit error nixvim](https://github.com/elythh/nixvim/assets/32416397/806dd8f7-7b09-4bde-b1d2-b4492126732d)

**Comment by elythh** [comment]
That's true, ill disable it by default

**Comment by elythh** [comment]
done 0cc7fce7791301ab3a447deb4342144a0e37d3c2
